train_batch_size: 8
val_batch_size: 8
num_workers: 2
input_size: 512
backbone: regnety_120
augmentation_func: peko.augmentation.get_augv5

total_epochs: 10
train_dataset: hotelid
n_classes: 3200

pretrained_model: null
pretrained_remove_fc: null

optimizer:
  fqdn: torch.optim.AdamW
  kwargs:
    lr: 0.0001

scheduler:
  fqdn: torch.optim.lr_scheduler.CosineAnnealingLR
  kwargs:
    T_max: 1
    eta_min: 0.000001

eval_dataset:
  - hotelid
